import {
    MatToolbarModule,
    MatButtonModule,
    MatInputModule,
    MatIconModule,
    MatCardModule,
    MatSelectModule,
    MatPaginatorModule,
    MatCheckboxModule,
    MatDividerModule,
    MatStepperModule,
    MatMenuModule,
    MatTooltipModule,
    MatRadioModule,
    MatFormFieldModule,
    MatChipsModule,
    MatSidenavModule,
    MatBadgeModule,
    MatListModule,
    MatExpansionModule,
    MatProgressSpinnerModule,
    MatSnackBarModule,
    MatTabsModule,
    MatProgressBarModule,
    MatAutocompleteModule,
    MatDatepickerModule,
    MatNativeDateModule,
    MatSlideToggleModule,
    MatSliderModule,
    MatTableModule
  } from '@angular/material';
import {OverlayModule} from '@angular/cdk/overlay';
import {ScrollingModule} from '@angular/cdk/scrolling';

export const materials = [
    MatToolbarModule,
    MatButtonModule,
    MatInputModule,
    MatIconModule,
    MatCardModule,
    MatSelectModule,
    MatPaginatorModule,
    MatCheckboxModule,
    MatDividerModule,
    MatStepperModule,
    MatMenuModule,
    MatTooltipModule,
    MatRadioModule,
    MatFormFieldModule,
    MatChipsModule,
    MatSidenavModule,
    OverlayModule,
    MatBadgeModule,
    MatListModule,
    MatExpansionModule,
    MatProgressSpinnerModule,
    MatSnackBarModule,
    ScrollingModule,
    MatTabsModule,
    MatProgressBarModule,
    MatAutocompleteModule,
    MatDatepickerModule,
    MatNativeDateModule,
    MatSlideToggleModule,
    MatSliderModule,
    MatTableModule
];
